name: Schedule Scraper

on:
  schedule:
    - cron: '0 */2 * * *' 

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt  

    - name: Run Scraper
      run: python otipy_scrape.py  # Replace with the path to your Python script
      
    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v5
      
